### ISSUE TITLE
where is the Docs

### ISSUE THREAD

**Issue by lvchangqi** [NewDadaFE/vue-impression#1]
I'm very interested in your project, but there is no docs in readme?

**Comment by shenlq** [comment]
小哥，我很欣赏你这种欣赏这个项目的眼光，文档正在马不停蹄地编写中。你要是很急，demo的源码暂时可以帮你一把。

**Comment by lvchangqi** [comment]
@shenlq 你这套UI真的很棒,感谢你的贡献, 我正在看demo的源码

**Comment by lvchangqi** [comment]
@shenlq 您好 请问demo的源码在哪里...

**Comment by shenlq** [comment]
demo源码在src/scripts/views这个目录下

**Comment by lvchangqi** [comment]
感谢您 我现在已经开始愉快的用这个UI框架了

**Comment by shenlq** [comment]
我们最近也在大规模使用，中间可能会有比较频繁地升级，保持关注。另外，欢迎建议和提bug
