### ISSUE TITLE
navbar    错位问题没有解决    刚刚下了最新的包  yarn install  本地开发模式有错位问题 附图

### ISSUE THREAD

**Issue by jiahua1** [NewDadaFE/vue-impression#10]
![df7c2ebb-5c2d-4fbc-89a7-8b511c977d19](https://cloud.githubusercontent.com/assets/11866846/22884598/ae86a286-f230-11e6-8373-54c5a42c4b38.png)

**Comment by shenlq** [comment]
版本号是？最新的应该是：0.9.29

**Comment by jiahua1** [comment]
<img width="499" alt="de0e3b2f-c59a-491a-8fac-6b4abcf4c0ef" src="https://cloud.githubusercontent.com/assets/11866846/22911308/f1ccaa9a-f299-11e6-8dce-8ab4d7c9be30.png">

**Comment by shenlq** [comment]
浏览器版本再爆一下

**Comment by jiahua1** [comment]
![7b8535d8-44c9-4847-9b62-460ce6c3cf8f](https://cloud.githubusercontent.com/assets/11866846/22912134/70455116-f29e-11e6-9cc4-74cd5e673ab0.png)

**Comment by shenlq** [comment]
![image](https://cloud.githubusercontent.com/assets/9411035/22912176/a3f99724-f29e-11e6-830f-a211a54159f8.png)

**Comment by jiahua1** [comment]
我这里也是有时有问题有时没问题， 方便加qq吗    2594857151

**Comment by shenlq** [comment]
fix 0.9.30
