### ISSUE TITLE
控件在尺寸上太大了

### ISSUE THREAD

**Issue by DevilLeven** [NewDadaFE/vue-impression#17]
组件很好，但是从demo来开，所有控件在尺寸上太大了，用这套组件做主体风格，会显得控件尺寸太大，不精致。

**Comment by shenlq** [comment]
我们针对 resolution：2dppx和resolution: 3dppx做了根元素字体大小的设置，把这两段去掉或者重写就变成所有终端一样的大小，但在分辨比比较高的手机上会显小。

@media only screen
and (min-device-width : 320px)
and (min-resolution: 2dppx) {
    html {
        font-size: $font-size-root-lg;
    }
}

// iphone 6/7 plus
@media only screen
and (min-device-width : 414px)
and (min-resolution: 3dppx) {
    html {
        font-size: $font-size-root-lgest;
    }
}
