### ISSUE TITLE
单独引入vue-impression.js做开发时，$toast只能显示默认样式

### ISSUE THREAD

**Issue by xiaoxin213** [NewDadaFE/vue-impression#19]
检查元素发现
<div class="toast toast-center toast-lg" style="display: none;">
<div class="toast-icon">
<icon name="exclamation-circle"></icon>
</div>
 <div class="toast-message">暂未开通此功能</div>
</div>

<icon name="exclamation-circle"></icon> 这一句应该是error的ico
使用代码：this.$toast({
                    type: 'error',
                    message: '暂未开通此功能',
                    position: 'center',
                });
求赐教，是不是使用错了。

**Comment by shenlq** [comment]
你打开的示例页面有引入fontawesome，你需要引用下。

**Comment by xiaoxin213** [comment]
确实不可用，我单元测试了很多次，没有error样式，检查元素 是 icon name='exclamation-triangle',
在这边下载的vue-impression.js，里面好像没有stepBar组件，可否请你再帮忙看一下
