### ISSUE TITLE
flex布局配合其他组件使用时会强制出现横向滚动条

### ISSUE THREAD

**Issue by lvchangqi** [NewDadaFE/vue-impression#2]
使用flex-item包裹searchbar之后会出现横向滚动条

**Comment by shenlq** [comment]
贴一下你的代码

**Comment by lvchangqi** [comment]
`  <div id="container">
    <flex class="row">
            <flex-item flex="8" class="bg-primary text-center item">
              <cell>
                  <searchbar shape="circle">
                      <searchbar-placeholder>
                          <icon name="search" left size="lg"></icon>搜索
                      </searchbar-placeholder>
                      <searchbar-btn>
                          <span class="text-primary">搜索</span>
                      </searchbar-btn>
                  </searchbar>
              </cell>
            </flex-item>
            <flex-item   class="item">5</flex-item>
        </flex>
    </div>`

**Comment by shenlq** [comment]
你要实现的是这样的效果吧：        <flex class="row">
            <flex-item>
                <group>
                    <cell>
                        <searchbar shape="circle"> <searchbar-placeholder> <icon name="search" left size="lg"></icon>搜索 </searchbar-placeholder> <searchbar-btn> <span class="text-primary">搜索</span> </searchbar-btn>
                        </searchbar>
                    </cell>
                </group>
            </flex-item>
        </flex>

**Comment by shenlq** [comment]
`        <flex class="row">
            <flex-item>
                <group>
                    <cell>
                        <searchbar shape="circle"> <searchbar-placeholder> <icon name="search" left size="lg"></icon>搜索 </searchbar-placeholder> <searchbar-btn> <span class="text-primary">搜索</span> </searchbar-btn>
                        </searchbar>
                    </cell>
                </group>
            </flex-item>
        </flex>`
