### ISSUE TITLE
Standalone Javascript file?

### ISSUE THREAD

**Issue by Ajusa** [NewDadaFE/vue-impression#4]
Hi,
I see that you are using webpack for everything. Not everyone uses webpack, some people just use vanilla html and css, with no build system. Where can I get the prebuilt javascript so I can include it as a script tag?

**Comment by Ajusa** [comment]
Please tell me if you need more clarification.
I don't want to use a build system. I want to be able to drop in ES5 script tags and have it work. I don't want to import anything.

Also, I really love the design and the ease of use of this framework. I think it is amazing!

**Comment by bipedd** [comment]
@Ajusa There will be a prebuilt version late today. Stay tuned.

**Comment by bipedd** [comment]
@Ajusa The prebuilt version is available now. Go ahead and have a try. [https://github.com/NewDadaFE/vue-impression#download](https://github.com/NewDadaFE/vue-impression#download)

**Comment by Ajusa** [comment]
@bipedd Wow okay! Thanks for responding back so quickly!

I'll use this as much as possible now.
