### ISSUE TITLE
Input Number and Input Text Suggestion

### ISSUE THREAD

**Issue by Ajusa** [NewDadaFE/vue-impression#5]
Hey,
I have been working with this framework, and I just wanted to say, it has been awesome.
One of the issues I ran into was creating a number input that had more that one digit, for a id feature. The id's are 4 digits long. This doesn't work well with the number input that is provided. To get around this, I ended up using this:

```
<div class="input-text">
                    <input type="number" v-model="d.team" class="input-text-input" placeholder="Number">
                </div>
```

It would be nice if this could be added to the input text as a type. In the source there is an exception for tel, maybe add one for number?

**Comment by shenlq** [comment]
@Ajusa thanks for your suggestion! It is fixed in 0.9.24.

**Comment by Ajusa** [comment]
@shenlq Wow, that's great!
Don't forget to update the compiled JS and CSS.

I'll see if I can also make some pull requests as I use this framework!

**Comment by shenlq** [comment]
Great, it is updated.
