### ISSUE TITLE
tabbar    有bug   切换时下面横线不会随状态变化。

### ISSUE THREAD

**Issue by jiahua1** [NewDadaFE/vue-impression#6]

**Comment by shenlq** [comment]
描述详细点，什么情况下？

**Comment by jiahua1** [comment]
cli起项目 yarn install   npm run start      点击tabbar  点击时对应的文字会点亮   但是下边的蓝色横条没有随对应点亮文字的位置变化而变化。

**Comment by shenlq** [comment]
浏览器版本？你访问demo：https://newdadafe.github.io/impression_vue/#/button会有异常吗？

**Comment by shenlq** [comment]
已修复：0.9.28。感谢反馈！！！
