### ISSUE TITLE
使用CNPM安装后，import Impression报找不到package.json 

### ISSUE THREAD

**Issue by bensonzhow** [NewDadaFE/vue-impression#7]
使用CNPM安装后，import Impression报找不到package.json 

位置webpack:///./~/.0.9.25@vue-impression/dist/scripts/components/index.js
......
var _loading = require('../utils/loading');

var _loading2 = _interopRequireDefault(_loading);

var _disfavor = require('../directives/disfavor');

var _disfavor2 = _interopRequireDefault(_disfavor);

var _package = require('../../../package.json');-------->此行报错Uncaught Error: Cannot find module "../../../package.json"

**Comment by shenlq** [comment]
import vue-impression from 'vue-impression';

**Comment by bensonzhow** [comment]
import Impression from 'vue-impression';
Vue.use(Impression);
使用方式是正确的，在使用任意components才会报错
环境如下
node version v6.9.1
npm version 3.10.8
cnpm version 4.4.2

**Comment by shenlq** [comment]
好了，升级到0.9.26，再试一下。不过我在
cnpm@4.5.0 
npm@3.10.10
node@6.3.1 
下0.9.25也没问题的。

**Comment by jiahua1** [comment]
我是好用的， 推荐使用 yarn install

**Comment by shenlq** [comment]
@jiahua1 同学，使用很积极哦！我看好你
